# abbrev.py
# part of Arcturus, a programming language and compiler for the Infocom Z-machine.
# Copyright (c) 2026, Stefan Vogt.
# https://github.com/ByteProject/Arcturus

"""Abbreviation selection, the B6 text-compression lever (docs/00 section 5).

Most of a story file is text. The Z-machine lets a string reference one of 96
abbreviations with two Z-characters (a bank shift 1..3 then an index 0..31), so a
substring that recurs across the program's strings is worth storing once and
referencing. This module chooses which substrings, two ways:

- DEFAULT_ABBREVS is a fixed set, computed once from the Cosmos library text and
  baked in, so every game gets useful compression with no extra step. It is
  regenerated by tools/arcabbr.py (which calls compute() over a representative
  corpus) and pasted back here; nothing recomputes it at compile time.
- compute() is the optimizer the `--make-abbreviations` pass runs over one game's
  pooled strings to write a tuned abbreviations.granule (docs/03 section 4), the
  opt-in that beats the default for a specific game.

The encoder applies whichever set is installed (zstring.set_abbreviations); this
module only decides the set. Selection is greedy with an EXACT objective: each
round measures candidates' true byte gain by running the encoder's own optimal
parse (padding included, storage subtracted) and takes the best, with a cleanup
pass dropping entries later picks made worthless. Provable optimality is NP-hard;
sharing the encoder's cost model end to end is the zabbrev-class lever that
matters in practice.
"""

from __future__ import annotations

from . import zstring

def _zlen(s: str) -> int:
    """The number of Z-characters the literal text of `s` encodes to (a capital or
    punctuation costs two, a ZSCII escape four), which is what an abbreviation
    saves per use beyond the two-Z-char reference."""
    return sum(len(zstring._char_to_zchars(c)) for c in s)


def _bytes_of(zchars: int) -> int:
    """Story-file bytes for a string of `zchars` Z-characters: packed three to a
    word, padded up, two bytes a word (an empty string still takes one word)."""
    words = (zchars + 2) // 3
    if words == 0:
        words = 1
    return words * 2


def _parse_cost(text: str, matchers) -> int:
    """Z-chars of the OPTIMAL parse of `text` under the abbreviation set, the
    same DP the encoder runs (zstring._text_to_zchars); selection and encoding
    share one cost model, so a predicted saving is a real saving."""
    return len(zstring._text_to_zchars(text, matchers))


def _corpus_bytes(strings, matchers) -> int:
    """Total story-file bytes for the pooled strings under the set: each
    string's padded words, plus the abbreviation strings' own literal storage.
    The 96-entry table itself is fixed layout, the same for every set, so it
    stays out of the objective."""
    total = 0
    for s in strings:
        total += _bytes_of(_parse_cost(s, matchers))
    for m in matchers:
        total += _bytes_of(_zlen(m[0]))
    return total


def _candidates(pool: list[str], min_len: int, max_len: int) -> dict:
    """Every substring worth considering, with its overlapping occurrence count
    across the pool. Built level by level (the Apriori property: a substring can
    only repeat if its prefix repeats), pruning count < 2 at each length, so
    memory holds survivors only."""
    prev: dict[str, int] | None = None
    cands: dict[str, int] = {}
    L = min_len
    while L <= max_len:
        level: dict[str, int] = {}
        for s in pool:
            top = len(s) - L
            for i in range(top + 1):
                sub = s[i : i + L]
                if prev is not None and sub[:-1] not in prev:
                    continue
                level[sub] = level.get(sub, 0) + 1
        level = {k: v for k, v in level.items() if v >= 2}
        if not level:
            break
        cands.update(level)
        prev = level
        L += 1
    return cands


def compute(strings, limit: int = zstring.ABBREV_MAX, min_len: int = 2, max_len: int = 40) -> list[str]:
    """Choose up to `limit` abbreviations for a pool of strings, best first.

    The objective is EXACT story-file bytes, not Z-chars: each round shortlists
    candidates by an optimistic bound, then measures each one's true byte gain
    by re-running the encoder's own optimal parse over the strings it touches
    (padding to the 3-Z-char word included, the abbreviation's own storage
    subtracted). The candidate with the largest measured gain wins the slot; a
    final pass drops any entry whose marginal value fell to nothing once later
    picks absorbed its text, freeing the slot for the next-best candidate.
    Selection and encoding share one cost model (the zabbrev lesson), so the
    predicted total is the byte total the story file shows."""
    pool = [s for s in strings if s]
    if not pool:
        return []
    import heapq

    cands = _candidates(pool, min_len, max_len)
    zlens = {sub: _zlen(sub) for sub in cands}
    containing = {}  # candidate -> indices of pool strings that hold it (lazy)

    def holders(sub: str):
        got = containing.get(sub)
        if got is None:
            got = [i for i, s in enumerate(pool) if sub in s]
            containing[sub] = got
        return got

    chosen: list[str] = []
    chosen_set: set[str] = set()
    cur_bytes = [_bytes_of(_zlen(s)) for s in pool]

    def exact_gain(sub: str) -> int:
        tm = zstring._build_matchers(chosen + [sub])
        gain = 0
        for i in holders(sub):
            gain += cur_bytes[i] - _bytes_of(_parse_cost(pool[i], tm))
        return gain - _bytes_of(zlens[sub])

    def take(sub: str) -> None:
        chosen.append(sub)
        chosen_set.add(sub)
        tm = zstring._build_matchers(chosen)
        for i in holders(sub):
            cur_bytes[i] = _bytes_of(_parse_cost(pool[i], tm))

    # Lazy greedy over a priority queue. Every candidate starts at an
    # optimistic byte bound (all overlapping occurrences paid in full, padding
    # luck included); popping re-measures the TRUE gain against the current
    # set and re-inserts unless the fresh value still tops the queue. Gains
    # only sink as picks absorb text, so a fresh value that beats the next
    # stale bound is the round's true maximum (the classic lazy-greedy
    # argument), and candidates that fell to nothing stop clogging the top.
    heap: list = []
    for sub, cnt in cands.items():
        bound = 2 * cnt * max(1, zlens[sub] - 2)
        heap.append((-bound, sub))
    heapq.heapify(heap)

    def pick_one():
        while heap:
            negg, sub = heapq.heappop(heap)
            if sub in chosen_set:
                continue
            gain = exact_gain(sub)
            if gain <= 0:
                continue  # sunk; out of the queue for good
            if not heap or -heap[0][0] <= gain:
                return sub, gain
            heapq.heappush(heap, (-gain, sub))
        return None, 0

    while len(chosen) < limit:
        best, best_gain = pick_one()
        if best is None:
            break
        take(best)

    # The cleanup pass: a pick made early can lose its worth once later picks
    # cover the same text. Measure each entry's marginal value against the
    # final set; drop the worthless and refill from what remains in the queue.
    for _ in range(2):
        dropped = False
        fm = zstring._build_matchers(chosen)
        for sub in list(chosen):
            rm = zstring._build_matchers([c for c in chosen if c != sub])
            marginal = 0
            for i in holders(sub):
                marginal += _bytes_of(_parse_cost(pool[i], rm)) - _bytes_of(_parse_cost(pool[i], fm))
            marginal -= _bytes_of(zlens[sub])
            if marginal <= 0:
                chosen.remove(sub)
                chosen_set.discard(sub)
                dropped = True
                fm = zstring._build_matchers(chosen)
        if not dropped:
            break
        tm = zstring._build_matchers(chosen)
        cur_bytes = [_bytes_of(_parse_cost(s, tm)) for s in pool]
        while len(chosen) < limit:
            best, best_gain = pick_one()
            if best is None:
                break
            take(best)
    return chosen


# The baked-in default set (tools/arcabbr.py regenerates this from the library
# corpus; see module docstring). Empty until first generated, which simply means
# no default compression until the set is filled in.
DEFAULT_ABBREVS: list[str] = [
    'You ',
    'thing',
    "n't ",
    ' already ',
    ' to ',
    ' the ',
    ' like to RESTART, RESTORE a saved game,',
    ' you',
    ' and ',
    ' with ',
    'ing',
    ' is',
    "There's no",
    'ranscript',
    ', ',
    "You'",
    " doesn't ",
    ' that',
    'The ',
    '[Score notification is',
    'locked.',
    'n it goes',
    ' have to ',
    ' no',
    ' nothing',
    ' of',
    'e.',
    ' fir',
    'Nothing',
    'be more specific.',
    ' carrying',
    ' from ',
    'It is',
    "You aren't",
    'Your ',
    'close',
    'here.',
    'open',
    'oursel',
    'surprise',
    't.',
    ' QUIT?',
    ' abou',
    ' conversatio',
    ' of a',
    ' your ',
    '.]',
    'ake',
    'et in',
    'me ',
    'n.',
    've ',
    ' an',
    ' can see ',
    ' dark',
    ' for ',
    ' happens',
    ' is not ',
    ' it.',
    ' just ',
    ' mean',
    ' now.',
    ' on',
    ' switch',
    ' under',
    '. ',
    'Do',
    'That',
    'a single ',
    'all',
    'ave ',
    'bject',
    'cor',
    'ear',
    'eep',
    'expected',
    'hands ',
    'here i',
    'running.',
    'shut.',
    'start',
    'worth',
]
