# abbrev.py
# part of Arcturus, a programming language and compiler for the Infocom Z-machine.
# Copyright (c) 2026, Stefan Vogt.
# https://github.com/ByteProject/Arcturus

"""Abbreviation selection, the B6 text-compression lever (docs/00 section 5).

Most of a story file is text. The Z-machine lets a string reference one of 96
abbreviations with two Z-characters (a bank shift 1..3 then an index 0..31), so a
substring that recurs across the program's strings is worth storing once and
referencing. This module chooses which substrings, two ways:

- DEFAULT_ABBREVS is a fixed set, computed once from the Cosmos library text and
  baked in, so every game gets useful compression with no extra step. It is
  regenerated by tools/arcabbr.py (which calls compute() over a representative
  corpus) and pasted back here; nothing recomputes it at compile time.
- compute() is the optimizer the `--make-abbreviations` pass runs over one game's
  pooled strings to write a tuned abbreviations.granule (docs/03 section 4), the
  opt-in that beats the default for a specific game.

The encoder applies whichever set is installed (zstring.set_abbreviations); this
module only decides the set. The selection is a greedy heuristic: repeatedly take
the substring whose references would save the most bytes, then mark its
occurrences so overlapping candidates are re-scored, until the table is full or
nothing else pays. It is not provably optimal (that problem is NP-hard), but it
matches what the encoder does at pack time (greedy, longest-first, non-
overlapping) and what zabbrv-style tools achieve in practice.
"""

from __future__ import annotations

from . import zstring

# A sentinel that cannot occur in source text (the lexer never admits a NUL), used
# to blank out an abbreviation's occurrences between rounds so a later candidate
# does not count text already claimed.
_SENT = "\x00"


def _zlen(s: str) -> int:
    """The number of Z-characters the literal text of `s` encodes to (a capital or
    punctuation costs two, a ZSCII escape four), which is what an abbreviation
    saves per use beyond the two-Z-char reference."""
    return sum(len(zstring._char_to_zchars(c)) for c in s)


def _score_candidates(work: list[str], min_len: int, max_len: int) -> dict:
    """Count every substring (length min_len..max_len, sentinel-free) across the
    working corpus. The count is the overlapping occurrence count, a fast and good
    enough proxy for ranking; the real saving is settled by re-scoring each round."""
    counts: dict[str, int] = {}
    for s in work:
        n = len(s)
        for i in range(n):
            if s[i] == _SENT:
                continue
            hi = min(max_len, n - i)
            for L in range(min_len, hi + 1):
                sub = s[i : i + L]
                if _SENT in sub:
                    break
                counts[sub] = counts.get(sub, 0) + 1
    return counts


def _saving(sub: str, count: int) -> int:
    """Z-chars saved by abbreviating `sub` that occurs `count` times: each use drops
    from _zlen(sub) to 2, less the one-time cost of storing the string. The table
    word (2 bytes) is a fixed per-entry overhead and does not affect the ranking."""
    return count * (_zlen(sub) - 2) - _zlen(sub)


def compute(strings, limit: int = zstring.ABBREV_MAX, min_len: int = 2, max_len: int = 20) -> list[str]:
    """Choose up to `limit` abbreviations for a pool of strings, best first. Each
    round scores all candidate substrings, takes the one that saves the most (if
    any still pays), and blanks its occurrences so the next round re-scores against
    what is left. Returns the chosen substrings in selection order (the index
    order the encoder and the table use)."""
    work = [s for s in strings if s]
    chosen: list[str] = []
    while len(chosen) < limit:
        counts = _score_candidates(work, min_len, max_len)
        best = None
        best_save = 0
        for sub, count in counts.items():
            if count < 2:
                continue
            save = _saving(sub, count)
            # Tie-break on longer text, then lexicographically, so the result is
            # deterministic regardless of dict iteration order.
            if save > best_save or (save == best_save and best is not None and (len(sub), sub) > (len(best), best)):
                best_save = save
                best = sub
        if best is None or best_save <= 0:
            break
        chosen.append(best)
        work = [s.replace(best, _SENT) for s in work]
    return chosen


# The baked-in default set (tools/arcabbr.py regenerates this from the library
# corpus; see module docstring). Empty until first generated, which simply means
# no default compression until the set is filled in.
DEFAULT_ABBREVS: list[str] = [
    'The ',
    "n't ",
    'thing ',
    'You',
    ' already ',
    'the ',
    "There's no",
    ' is ',
    ' to ',
    ' with ',
    ' you',
    ' does',
    'ing',
    't.',
    'ocked.',
    ' have',
    ' and ',
    'here.',
    ' it ',
    'ck.',
    'close',
    'n.',
    "'re carry",
    'about ',
    'es.',
    ' a ',
    'It',
    'too dark',
    'hat save',
    't in ',
    'nside',
    ' what',
    "'ll",
    ' no',
    ', ',
    'all',
    ' is',
    'No',
    'switch',
    'plain ',
    'keeper',
    ' leave',
    'room',
    'ight',
    ' see',
    ' of ',
    ' for',
    ' fir',
    ' are',
    'wor',
    'ver',
    'ed.',
    'ant',
    'ellar',
    ' feel',
    ' desk',
    'one.',
    'to ',
    'ome',
    'old',
    'ly ',
    'her',
    'be ',
    'an ',
    ': "',
    ' on',
    ' an',
    's.',
]
