# dress.py
# part of Actaea, the Arcturus reference Z-machine interpreter.
# Copyright (c) 2026, Stefan Vogt.
# https://github.com/ByteProject/Arcturus
#
# THE NATIVE DRESSING (Actaea 2.0): how a zero-dependency Python script
# presents as a real application on every desktop, without installing
# anything it was not asked to.
#
# Two layers, deliberately separate:
#
# 1. SELF-DRESSING, every window launch, no bundle involved. Before Tk
#    exists, the process takes its own name: on macOS the menu bar shows
#    the CFBundleName of the hosting bundle (bare Python's says Python),
#    and that name is rewritten in memory through ctypes/objc, proven on
#    the target machine before this module was written (probes/
#    macdress_probe.py). On Windows the taskbar identity is claimed with
#    an AppUserModelID. Once the window exists, it wears Stefan's star:
#    the Dock icon on macOS, the title-bar/taskbar icon everywhere.
#
# 2. THE STUB, only on explicit request (`actaea --install-app`). A thin
#    launcher goes where the desktop looks for applications: a macOS
#    Actaea.app whose three-line shim execs the real interpreter, a Linux
#    .desktop entry, a Windows Start Menu shortcut with file
#    associations. The stub holds NO logic, so it can never go stale
#    against updates: the core application stays where it was downloaded,
#    beside arcc and the other Arcturus tools, and `arcc --update` keeps
#    them all current; the stub follows automatically. Double-clicked
#    stories reach the window as Apple Events (Tk's ::tk::mac::
#    OpenDocument) on macOS and as plain arguments elsewhere.
#
# Like the faces (fonts.py), the icons ride embedded in the standalone
# (gui.icondata, generated by the amalgamator) and unpack once to the
# user data directory. And like the faces: dressing can never raise.
# An undressed session still plays.

import os
import sys

APP_NAME = "Actaea"
BUNDLE_ID = "org.byteproject.actaea"
# The extensions the interpreter opens (docs/06: z5 and z8, plus the
# Blorb wrapper); the dialogs and the associations name the same three.
STORY_EXTENSIONS = ("z5", "z8", "zblorb")


# -- the icon files ---------------------------------------------------------

def icons_dir() -> str:
    # In the standalone there is no real directory behind this module (its
    # loader-supplied __file__ is a virtual path): the directory then does
    # not exist and the embedded icons take over, exactly like the fonts.
    here = globals().get("__file__") or ""
    return os.path.join(os.path.dirname(os.path.abspath(here)), "icons")


def _icon_files() -> list:
    d = icons_dir()
    try:
        files = [os.path.join(d, f) for f in sorted(os.listdir(d))
                 if f.lower().endswith((".icns", ".ico", ".png"))]
    except OSError:
        files = []
    if files:
        return files
    return _unpacked_files()


def _unpacked_files() -> list:
    """The standalone: the icons ride inside as base64 (gui.icondata, a
    module the amalgamator generates) and unpack ONCE into the user data
    directory beside the fonts; later launches find them already there."""
    try:
        from . import icondata
    except ImportError:
        return []
    import base64
    base = os.environ.get("XDG_DATA_HOME",
                          os.path.join(os.path.expanduser("~"),
                                       ".local", "share"))
    dest = os.path.join(base, "actaea", "icons")
    try:
        os.makedirs(dest, exist_ok=True)
        out = []
        for name, blob in sorted(icondata.ICONS.items()):
            path = os.path.join(dest, name)
            data = base64.b64decode(blob)
            if not (os.path.exists(path)
                    and os.path.getsize(path) == len(data)):
                with open(path, "wb") as fh:
                    fh.write(data)
            out.append(path)
        return out
    except OSError:
        return []


def icon_path(name: str):
    """The on-disk path of one icon file (say "actaea.icns"), or None."""
    for path in _icon_files():
        if os.path.basename(path) == name:
            return path
    return None


# -- layer one: the process dresses itself ----------------------------------

_predressed = False


def predress() -> None:
    """Claim the process identity, BEFORE any Tk root exists: macOS
    snapshots the menu bar name when NSApplication launches, and Windows
    groups taskbar windows by the AppUserModelID they started with.
    Idempotent; never raises."""
    global _predressed
    if _predressed:
        return
    _predressed = True
    try:
        if sys.platform == "darwin":
            _take_name_mac()
        elif sys.platform == "win32":
            import ctypes
            ctypes.windll.shell32.SetCurrentProcessExplicitAppUserModelID(
                "ByteProject.Actaea")
    except Exception:
        pass


def _take_name_mac() -> None:
    """Rewrite CFBundleName in the hosting bundle's in-memory info
    dictionary, so the menu bar reads Actaea instead of Python. Not
    documented API, but proven on the target machine (probes/
    macdress_probe.py: Homebrew Python.app's dictionary is a mutable
    __NSDictionaryM, and the menu bar followed); every step is guarded,
    and a machine where the dictionary is immutable simply keeps the
    old name. The write must precede the first Tk root."""
    import ctypes
    import ctypes.util
    libobjc = ctypes.CDLL(ctypes.util.find_library("objc"))
    ctypes.CDLL(ctypes.util.find_library("AppKit"))
    libobjc.objc_getClass.restype = ctypes.c_void_p
    libobjc.objc_getClass.argtypes = [ctypes.c_char_p]
    libobjc.sel_registerName.restype = ctypes.c_void_p
    libobjc.sel_registerName.argtypes = [ctypes.c_char_p]
    msg = ctypes.cast(libobjc.objc_msgSend, ctypes.c_void_p).value

    def send(obj, selname, args=(), argtypes=(), restype=ctypes.c_void_p):
        proto = ctypes.CFUNCTYPE(restype, ctypes.c_void_p, ctypes.c_void_p,
                                 *argtypes)
        return proto(msg)(obj, libobjc.sel_registerName(selname.encode()),
                          *args)

    def nss(text):
        return send(libobjc.objc_getClass(b"NSString"),
                    "stringWithUTF8String:", (text.encode("utf-8"),),
                    (ctypes.c_char_p,))

    bundle = send(libobjc.objc_getClass(b"NSBundle"), "mainBundle")
    for selname in ("infoDictionary", "localizedInfoDictionary"):
        info = send(bundle, selname)
        if not info:
            continue
        mutable = send(info, "respondsToSelector:",
                       (libobjc.sel_registerName(b"setObject:forKey:"),),
                       (ctypes.c_void_p,), restype=ctypes.c_bool)
        if mutable:
            for key in ("CFBundleName", "CFBundleDisplayName"):
                send(info, "setObject:forKey:",
                     (nss(APP_NAME), nss(key)),
                     (ctypes.c_void_p, ctypes.c_void_p))


def _take_dock_name_mac() -> None:
    """The Dock's hover label is LaunchServices' display name for the
    running application, held in its process registration (the ASN), not
    in the bundle dictionary: rewriting CFBundleName fixes the menu bar
    but the Dock still whispered Python (Stefan's hover, 2026-08-21).
    LaunchServices has a private setter for exactly this, the one Java
    and SDL have leaned on for years; the ASN exists only once the app
    has registered, so this runs AFTER the Tk root, from dress()."""
    import ctypes
    import ctypes.util
    ls = ctypes.CDLL(ctypes.util.find_library("CoreServices"))
    ls._LSGetCurrentApplicationASN.restype = ctypes.c_void_p
    ls._LSGetCurrentApplicationASN.argtypes = []
    ls._LSSetApplicationInformationItem.restype = ctypes.c_int
    ls._LSSetApplicationInformationItem.argtypes = [
        ctypes.c_int, ctypes.c_void_p, ctypes.c_void_p, ctypes.c_void_p,
        ctypes.c_void_p]
    cf = ctypes.CDLL(ctypes.util.find_library("CoreFoundation"))
    cf.CFStringCreateWithCString.restype = ctypes.c_void_p
    cf.CFStringCreateWithCString.argtypes = [ctypes.c_void_p,
                                             ctypes.c_char_p,
                                             ctypes.c_uint32]
    # The private key symbol when it exports, else the literal string
    # LaunchServices stores under (community-attested both ways).
    try:
        key = ctypes.c_void_p.in_dll(ls, "_kLSDisplayNameKey").value
    except ValueError:
        key = None
    if not key:
        key = cf.CFStringCreateWithCString(None, b"LSDisplayName", 0x08000100)
    name = cf.CFStringCreateWithCString(None, APP_NAME.encode("utf-8"),
                                        0x08000100)
    asn = ls._LSGetCurrentApplicationASN()
    if asn and key and name:
        ls._LSSetApplicationInformationItem(-2, asn, key, name, None)


def dress(root) -> None:
    """Put the star on the window that now exists: the Dock icon on
    macOS, the title-bar and taskbar icon everywhere Tk honors one.
    Never raises."""
    try:
        png = icon_path("actaea.png")
        if png:
            import tkinter as tk
            img = tk.PhotoImage(file=png)
            root.iconphoto(True, img)
            root._actaea_icon = img  # keep referenced or Tk drops it
    except Exception:
        pass
    if sys.platform == "darwin":
        try:
            _dock_icon_mac()
        except Exception:
            pass
        try:
            _take_dock_name_mac()
        except Exception:
            pass
    elif sys.platform == "win32":
        try:
            ico = icon_path("actaea.ico")
            if ico:
                root.iconbitmap(default=ico)
        except Exception:
            pass


def _dock_icon_mac() -> None:
    """setApplicationIconImage (documented API): the Dock tile becomes the
    star for this process's lifetime, nothing installed."""
    icns = icon_path("actaea.icns")
    if not icns:
        return
    import ctypes
    import ctypes.util
    libobjc = ctypes.CDLL(ctypes.util.find_library("objc"))
    ctypes.CDLL(ctypes.util.find_library("AppKit"))
    libobjc.objc_getClass.restype = ctypes.c_void_p
    libobjc.objc_getClass.argtypes = [ctypes.c_char_p]
    libobjc.sel_registerName.restype = ctypes.c_void_p
    libobjc.sel_registerName.argtypes = [ctypes.c_char_p]
    msg = ctypes.cast(libobjc.objc_msgSend, ctypes.c_void_p).value

    def send(obj, selname, args=(), argtypes=()):
        proto = ctypes.CFUNCTYPE(ctypes.c_void_p, ctypes.c_void_p,
                                 ctypes.c_void_p, *argtypes)
        return proto(msg)(obj, libobjc.sel_registerName(selname.encode()),
                          *args)

    path = send(libobjc.objc_getClass(b"NSString"), "stringWithUTF8String:",
                (icns.encode("utf-8"),), (ctypes.c_char_p,))
    image = send(libobjc.objc_getClass(b"NSImage"), "alloc")
    image = send(image, "initWithContentsOfFile:", (path,),
                 (ctypes.c_void_p,))
    if not image:
        return
    app = send(libobjc.objc_getClass(b"NSApplication"), "sharedApplication")
    send(app, "setApplicationIconImage:", (image,), (ctypes.c_void_p,))


# -- layer two: the stub (`actaea --install-app`) ---------------------------

def _core_command():
    """How to start THIS interpreter again: (argv list, pythonpath). The
    standalone is a real file (the amalgam's __main__ carries _BUILD_ID)
    and needs no path help; a source checkout is `python -m actaea` with
    the repository root importable."""
    main_mod = sys.modules.get("__main__")
    if getattr(main_mod, "_BUILD_ID", None) is not None:
        return [sys.executable, os.path.abspath(sys.argv[0])], None
    here = os.path.dirname(os.path.abspath(globals().get("__file__") or "."))
    repo = os.path.dirname(os.path.dirname(here))
    return [sys.executable, "-m", "actaea"], repo


def _core_marker(core: list, pythonpath) -> str:
    """The path refresh_stub watches for life: the amalgam file, or the
    source checkout's repository root."""
    return pythonpath if pythonpath else core[1]


_KEEP_TOGETHER = (
    "The core application stays where it was downloaded and must be kept\n"
    "together with arcc and the other Arcturus files, so that arcc --update\n"
    "keeps every tool current; the stub follows automatically.")


def install_app(applications_dir=None) -> int:
    """`actaea --install-app`: put the thin launcher where this desktop
    looks for applications. Returns a process exit code."""
    try:
        if sys.platform == "darwin":
            return _install_mac(applications_dir)
        if sys.platform == "win32":
            return _install_windows()
        return _install_linux()
    except OSError as e:
        print("actaea: could not install the launcher: %s" % e,
              file=sys.stderr)
        return 2


def _shim_lines(core: list, pythonpath) -> list:
    """The macOS shim: a few working lines and the paths they depend on,
    marked so refresh_stub can read the core path back."""
    import shlex
    lines = ["#!/bin/sh",
             "# Actaea stub, written by 'actaea --install-app'. The real",
             "# interpreter lives with the other Arcturus tools (kept",
             "# current by arcc --update); this bundle only lends it a",
             "# Finder face.",
             "# core: %s" % _core_marker(core, pythonpath),
             "ACTAEA_BUNDLE=1",
             "export ACTAEA_BUNDLE",
             # The recorded interpreter can vanish (a Homebrew upgrade
             # retires its versioned path); fall back to the PATH's
             # python3 rather than dying silently under a double-click.
             "PY=%s" % shlex.quote(core[0]),
             '[ -x "$PY" ] || PY=python3']
    if pythonpath:
        # A source checkout: the package must be importable.
        lines.append("PYTHONPATH=%s" % shlex.quote(pythonpath))
        lines.append("export PYTHONPATH")
    lines.append('exec "$PY" '
                 + " ".join(shlex.quote(w) for w in core[1:]) + ' "$@"')
    return lines


def _mac_bundle_dir(applications_dir=None) -> str:
    if applications_dir is None:
        applications_dir = "/Applications"
        if not os.access(applications_dir, os.W_OK):
            applications_dir = os.path.join(os.path.expanduser("~"),
                                            "Applications")
    return os.path.join(applications_dir, "%s.app" % APP_NAME)


def _write_mac_bundle(app: str, core: list, pythonpath) -> None:
    import plistlib
    import shutil
    from .. import __version__
    macos = os.path.join(app, "Contents", "MacOS")
    resources = os.path.join(app, "Contents", "Resources")
    os.makedirs(macos, exist_ok=True)
    os.makedirs(resources, exist_ok=True)

    plist = {
        "CFBundleName": APP_NAME,
        "CFBundleDisplayName": APP_NAME,
        "CFBundleIdentifier": BUNDLE_ID,
        "CFBundleExecutable": APP_NAME,
        "CFBundlePackageType": "APPL",
        "CFBundleShortVersionString": __version__,
        "CFBundleVersion": __version__,
        "CFBundleIconFile": "actaea",
        "NSHighResolutionCapable": True,
        "CFBundleDocumentTypes": [{
            "CFBundleTypeName": "Z-machine story",
            "CFBundleTypeRole": "Viewer",
            "CFBundleTypeIconFile": "actaea",
            "CFBundleTypeExtensions": list(STORY_EXTENSIONS),
        }],
    }
    with open(os.path.join(app, "Contents", "Info.plist"), "wb") as fh:
        plistlib.dump(plist, fh)

    shim = os.path.join(macos, APP_NAME)
    with open(shim, "w", encoding="utf-8") as fh:
        fh.write("\n".join(_shim_lines(core, pythonpath)) + "\n")
    os.chmod(shim, 0o755)

    icns = icon_path("actaea.icns")
    if icns:
        shutil.copy2(icns, os.path.join(resources, "actaea.icns"))


def _install_mac(applications_dir=None) -> int:
    core, pythonpath = _core_command()
    app = _mac_bundle_dir(applications_dir)
    _write_mac_bundle(app, core, pythonpath)
    # Nudge LaunchServices so Finder learns the associations now rather
    # than at the first launch; quietly optional.
    lsregister = ("/System/Library/Frameworks/CoreServices.framework/"
                  "Frameworks/LaunchServices.framework/Support/lsregister")
    if os.path.exists(lsregister):
        import subprocess
        try:
            subprocess.run([lsregister, "-f", app], capture_output=True,
                           timeout=30)
        except (OSError, subprocess.SubprocessError):
            pass
    print("Installed the %s stub.\n%s\ncore: %s"
          % (app, _KEEP_TOGETHER, _core_marker(core, pythonpath)))
    return 0


def refresh_stub(bases=None) -> None:
    """Silent healing at window launch, macOS only: when an installed
    stub's core path no longer exists (the download directory moved), and
    THIS process is that core reborn, rewrite the shim to point here. A
    stub pointing at a live core is never touched: running a second copy
    must not hijack the installed one. Never raises."""
    if sys.platform != "darwin" and bases is None:
        return
    try:
        core, pythonpath = _core_command()
        for base in (bases if bases is not None else
                     ("/Applications",
                      os.path.join(os.path.expanduser("~"),
                                   "Applications"))):
            app = os.path.join(base, "%s.app" % APP_NAME)
            shim = os.path.join(app, "Contents", "MacOS", APP_NAME)
            if not os.path.isfile(shim):
                continue
            with open(shim, encoding="utf-8") as fh:
                lines = fh.read().splitlines()
            marked = [ln for ln in lines if ln.startswith("# core: ")]
            if not marked:
                continue
            old = marked[0][len("# core: "):]
            if os.path.exists(old):
                continue
            _write_mac_bundle(app, core, pythonpath)
    except Exception:
        pass


def _install_linux() -> int:
    import shutil
    import subprocess
    core, pythonpath = _core_command()
    base = os.environ.get("XDG_DATA_HOME",
                          os.path.join(os.path.expanduser("~"),
                                       ".local", "share"))
    png = icon_path("actaea.png")
    if png:
        icon_dest = os.path.join(base, "icons", "hicolor", "512x512", "apps")
        os.makedirs(icon_dest, exist_ok=True)
        shutil.copy2(png, os.path.join(icon_dest, "actaea.png"))

    env_prefix = ""
    if pythonpath:
        env_prefix = "env PYTHONPATH=%s " % _desktop_quote(pythonpath)
    exec_line = (env_prefix
                 + " ".join(_desktop_quote(w) for w in core) + " %f")
    entry = "\n".join([
        "[Desktop Entry]",
        "Type=Application",
        "Name=%s" % APP_NAME,
        "Comment=Z-machine interpreter (Arcturus)",
        "Exec=%s" % exec_line,
        "Icon=actaea",
        "Terminal=false",
        "Categories=Game;Emulator;",
        "MimeType=application/x-zmachine;",
    ]) + "\n"
    apps = os.path.join(base, "applications")
    os.makedirs(apps, exist_ok=True)
    desktop = os.path.join(apps, "actaea.desktop")
    with open(desktop, "w", encoding="utf-8") as fh:
        fh.write(entry)

    for cmd in (["update-desktop-database", apps],
                ["gtk-update-icon-cache",
                 os.path.join(base, "icons", "hicolor")]):
        if shutil.which(cmd[0]):
            try:
                subprocess.run(cmd, capture_output=True, timeout=30)
            except (OSError, subprocess.SubprocessError):
                pass
    print("Installed %s.\n%s" % (desktop, _KEEP_TOGETHER))
    return 0


def _desktop_quote(word: str) -> str:
    """Desktop Entry Exec quoting: double quotes when the word needs them."""
    if all(c.isalnum() or c in "/._-:" for c in word):
        return word
    return '"' + word.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _install_windows() -> int:
    import subprocess
    import winreg
    core, pythonpath = _core_command()
    if pythonpath:
        # A source checkout on Windows: no clean way to carry PYTHONPATH
        # through a registry verb; the standalone is the installable form.
        print("actaea: --install-app on Windows needs the standalone "
              "actaea file, not a source checkout", file=sys.stderr)
        return 2
    # pythonw.exe keeps the console window away from a double-click.
    pyw = os.path.join(os.path.dirname(sys.executable), "pythonw.exe")
    python = pyw if os.path.isfile(pyw) else sys.executable
    target_args = subprocess.list2cmdline(core[1:] + ["%1"])
    ico = icon_path("actaea.ico") or ""

    classes = r"Software\Classes"
    with winreg.CreateKey(winreg.HKEY_CURRENT_USER,
                          classes + r"\Actaea.Story") as k:
        winreg.SetValue(k, "", winreg.REG_SZ, "Z-machine story")
    if ico:
        with winreg.CreateKey(winreg.HKEY_CURRENT_USER,
                              classes + r"\Actaea.Story\DefaultIcon") as k:
            winreg.SetValue(k, "", winreg.REG_SZ, ico)
    with winreg.CreateKey(
            winreg.HKEY_CURRENT_USER,
            classes + r"\Actaea.Story\shell\open\command") as k:
        winreg.SetValue(k, "", winreg.REG_SZ,
                        subprocess.list2cmdline([python]) + " " + target_args)
    for ext in STORY_EXTENSIONS:
        with winreg.CreateKey(winreg.HKEY_CURRENT_USER,
                              classes + "\\." + ext) as k:
            winreg.SetValue(k, "", winreg.REG_SZ, "Actaea.Story")

    # The Start Menu shortcut, through the shell's own COM object; a
    # machine with scripting locked down just skips it.
    lnk = os.path.join(os.environ.get("APPDATA", ""),
                       "Microsoft", "Windows", "Start Menu", "Programs",
                       "Actaea.lnk")
    script = (
        "$ws = New-Object -ComObject WScript.Shell; "
        "$s = $ws.CreateShortcut(%s); "
        "$s.TargetPath = %s; "
        "$s.Arguments = %s; "
        + ("$s.IconLocation = %s; " if ico else "")
        + "$s.Save()")
    quoted = [_ps_quote(lnk), _ps_quote(python),
              _ps_quote(subprocess.list2cmdline(core[1:]))]
    if ico:
        quoted.append(_ps_quote(ico))
    try:
        subprocess.run(["powershell", "-NoProfile", "-Command",
                        script % tuple(quoted)],
                       capture_output=True, timeout=60)
    except (OSError, subprocess.SubprocessError):
        pass
    print("Installed the story associations and Start Menu entry.\n"
          + _KEEP_TOGETHER)
    return 0


def _ps_quote(text: str) -> str:
    return "'" + text.replace("'", "''") + "'"
