#!/usr/bin/env python3
# amalgamate.py
# part of Arcturus, a programming language and compiler for the Infocom Z-machine.
# Copyright (c) 2026, Stefan Vogt.
# https://github.com/ByteProject/Arcturus

"""Build a single standalone `arcc` script from the arcturus/ package.

The compiler is developed as clean, separate modules (lexer, parser, ast,
semantic analysis, codegen, cli), as CLAUDE.md requires. For distribution to
the interactive-fiction community it must instead be one self-contained file
that runs on a bare Python interpreter with no installation and no package
directory: `python3 arcc game.storyarc`.

This tool reconciles the two. It embeds each module's source verbatim (no
rewriting, so the shipped code is identical to the package) and prepends a tiny
loader that reconstructs the package in memory and calls the CLI. The result is
a single script with zero runtime dependencies.

Usage:
    python3 tools/amalgamate.py [output_path]      # default: build/arcc
"""

from __future__ import annotations

import os
import stat
import sys

# The package __init__ is loaded first (it defines __version__), then the
# submodules in dependency order so the relative imports resolve from the
# already-registered modules.
_PACKAGE = "arcturus"
_MODULE_ORDER = [
    "errors", "tokens", "ast", "lexer", "parser", "prelude", "worldmodel",
    "sema", "zstring", "storyfile", "assembler", "objects", "dictionary",
    "lower", "cosmos", "codegen", "astdump", "irdump", "cli",
]

_HEADER = '''#!/usr/bin/env python3
# arcc
# part of Arcturus, a programming language and compiler for the Infocom Z-machine.
# Copyright (c) 2026, Stefan Vogt.
# https://github.com/ByteProject/Arcturus
#
# Standalone single-file build, generated by tools/amalgamate.py from the
# arcturus/ package. Do not edit by hand; edit the package and rebuild. The
# module sources below are embedded verbatim as string literals, so a few lines
# are very long; that is expected, not a syntax error.
#
# Run with a bare Python 3.11+ interpreter, no installation required:
#   python3 arcc game.storyarc

import sys
import types
'''

_LOADER = '''

def _bootstrap():
    pkg = types.ModuleType("arcturus")
    pkg.__package__ = "arcturus"
    pkg.__path__ = []
    sys.modules["arcturus"] = pkg
    exec(compile(_INIT, "arcturus/__init__.py", "exec"), pkg.__dict__)
    for name in _MODULE_ORDER:
        mod = types.ModuleType("arcturus." + name)
        mod.__package__ = "arcturus"
        sys.modules["arcturus." + name] = mod
        setattr(pkg, name, mod)
        exec(compile(_MODULES[name], "arcturus/" + name + ".py", "exec"), mod.__dict__)
    # Embed the Cosmos library so the single-file build carries it (no cosmos/
    # directory at run time).
    sys.modules["arcturus.cosmos"]._EMBEDDED = _COSMOS
    return sys.modules["arcturus.cli"]


if __name__ == "__main__":
    raise SystemExit(_bootstrap().main())
'''


def _read(pkg_dir: str, module: str) -> str:
    path = os.path.join(pkg_dir, module + ".py")
    with open(path, "r", encoding="utf-8") as fh:
        return fh.read()


def build(output_path: str) -> None:
    here = os.path.dirname(os.path.abspath(__file__))
    repo_root = os.path.dirname(here)
    pkg_dir = os.path.join(repo_root, _PACKAGE)

    init_src = _read(pkg_dir, "__init__")
    module_srcs = {name: _read(pkg_dir, name) for name in _MODULE_ORDER}

    # The Cosmos library sources, embedded so the single-file build carries them.
    cosmos_dir = os.path.join(repo_root, "cosmos")
    cosmos_srcs = {}
    if os.path.isdir(cosmos_dir):
        for name in sorted(os.listdir(cosmos_dir)):
            # The core library (.prelude) and the official summonable features
            # (.granule) both travel inside arcc.
            if name.endswith(".prelude") or name.endswith(".granule"):
                with open(os.path.join(cosmos_dir, name), "r", encoding="utf-8") as fh:
                    cosmos_srcs[name] = fh.read()

    parts = [_HEADER]
    parts.append(f"\n_MODULE_ORDER = {_MODULE_ORDER!r}\n")
    # repr() yields a valid, fully escaped Python string literal for any source.
    parts.append(f"\n_INIT = {init_src!r}\n")
    parts.append("\n_MODULES = {\n")
    for name in _MODULE_ORDER:
        parts.append(f"    {name!r}: {module_srcs[name]!r},\n")
    parts.append("}\n")
    parts.append("\n_COSMOS = {\n")
    for name in sorted(cosmos_srcs):
        parts.append(f"    {name!r}: {cosmos_srcs[name]!r},\n")
    parts.append("}\n")
    parts.append(_LOADER)
    script = "".join(parts)

    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as fh:
        fh.write(script)
    # Make it directly executable via its shebang.
    mode = os.stat(output_path).st_mode
    os.chmod(output_path, mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    print(f"wrote {output_path} ({len(script)} bytes)")


def main(argv: list[str]) -> int:
    output = argv[0] if argv else os.path.join("build", "arcc")
    build(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
