#!/usr/bin/env python3
# amalgamate_actaea.py
# part of Arcturus, a programming language and compiler for the Infocom Z-machine.
# Copyright (c) 2026, Stefan Vogt.
# https://github.com/ByteProject/Arcturus

"""Build a single standalone `actaea` script from the actaea/ package.

The interpreter is developed as clean, separate modules behind a hard io
boundary, as docs/06 requires. For distribution it must be one self-contained
file that runs on a bare Python interpreter: `python3 actaea story.z5`.

Same reconciliation as tools/amalgamate.py does for arcc: each module's
source is embedded verbatim, a tiny loader reconstructs the package in
memory. One difference matters here: the modules load LAZILY through an
import hook, because the front-ends pull in tkinter and curses, which not
every Python has; the single file must stay playable headless on any of
them, exactly like the package (whose __main__ imports front-ends only when
asked).

Usage:
    python3 tools/amalgamate_actaea.py [output_path]   # default: build/actaea
"""

from __future__ import annotations

import base64
import hashlib
import os
import stat
import sys

_PACKAGE = "actaea"

# Flat modules, the gui subpackage, and the entry, all lazy; the package
# __init__ (version and banner, no imports) is executed at bootstrap.
_MODULES = [
    "errors", "memory", "loader", "decode", "text", "dictionary", "objects",
    "screen", "quetzal", "io", "vm", "session", "console", "gui",
    "gui.fonts", "gui.dress", "gui.app", "__main__",
]

# NOTE: this list is the standalone's whole world. A module missing from it
# imports fine from the package and fails only in the built file, at the
# moment a player opens the window (a gui submodule shipped missing once,
# 2026-08-20, caught by the smoke test, not by the suite).

_HEADER = '''#!/usr/bin/env python3
# actaea
# part of Arcturus, a programming language and compiler for the Infocom Z-machine.
# Copyright (c) 2026, Stefan Vogt.
# https://github.com/ByteProject/Arcturus
#
# Standalone single-file build, generated by tools/amalgamate_actaea.py from
# the actaea/ package. Do not edit by hand; edit the package and rebuild. The
# module sources below are embedded verbatim as string literals, so a few
# lines are very long; that is expected, not a syntax error.
#
# Run with a bare Python 3.11+ interpreter, no installation required:
#   python3 actaea story.z5

import importlib.abc
import importlib.util
import sys
import types
'''

_LOADER = '''

class _EmbeddedFinder(importlib.abc.MetaPathFinder, importlib.abc.Loader):
    """Serves the embedded module sources to the ordinary import machinery,
    so relative imports, laziness, and optional front-ends (tkinter, curses)
    behave exactly as they do in the package."""

    def find_spec(self, name, path=None, target=None):
        if name in _MODULES:
            return importlib.util.spec_from_loader(
                name, self, is_package=(name == "actaea.gui")
            )
        return None

    def create_module(self, spec):
        return None  # the default module object is right

    def exec_module(self, module):
        src = _MODULES[module.__name__]
        path = module.__name__.replace(".", "/") + ".py"
        module.__dict__.setdefault("__file__", path)
        exec(compile(src, path, "exec"), module.__dict__)


def _bootstrap():
    pkg = types.ModuleType("actaea")
    pkg.__package__ = "actaea"
    pkg.__path__ = []
    sys.modules["actaea"] = pkg
    exec(compile(_INIT, "actaea/__init__.py", "exec"), pkg.__dict__)
    pkg.__build__ = _BUILD_ID  # stamp the fingerprint over the source default (None)
    sys.meta_path.insert(0, _EmbeddedFinder())
    import actaea.__main__ as entry

    return entry


if __name__ == "__main__":
    raise SystemExit(_bootstrap().main())
'''


def _read(pkg_dir: str, module: str) -> str:
    rel = module.replace(".", os.sep)
    path = os.path.join(pkg_dir, rel + ".py")
    if module == "gui":
        path = os.path.join(pkg_dir, "gui", "__init__.py")
    with open(path, "r", encoding="utf-8") as fh:
        return fh.read()


def _fingerprint(init_src: str, module_srcs: dict, modules=None) -> str:
    """A short content hash of exactly what this amalgam embeds: the package
    init (which carries __version__) and the modules in load order.
    Deterministic, so two builds with the same id are byte-identical and a
    different id is a genuinely different interpreter at the same version.
    __build__ in init_src is None here, so the hash never depends on itself."""
    h = hashlib.sha256()
    h.update(init_src.encode("utf-8"))
    for name in (modules if modules is not None else _MODULES):
        h.update(name.encode("utf-8"))
        h.update(module_srcs[name].encode("utf-8"))
    return h.hexdigest()[:7]


def build(output_path: str) -> None:
    here = os.path.dirname(os.path.abspath(__file__))
    repo_root = os.path.dirname(here)
    pkg_dir = os.path.join(repo_root, _PACKAGE)

    init_src = _read(pkg_dir, "__init__")
    modules = list(_MODULES)
    module_srcs = {name: _read(pkg_dir, name) for name in modules}
    # THE FACES RIDE INSIDE, like Cosmos rides inside arcc: the fonts
    # directory becomes a synthetic module of base64 blobs, and gui/fonts.py
    # unpacks it to the user data directory on first run when the loose
    # files are not beside it (the standalone case).
    fonts_dir = os.path.join(pkg_dir, "gui", "fonts")
    blobs = []
    for fn in sorted(os.listdir(fonts_dir)):
        if fn.lower().endswith((".ttf", ".otf")):
            data = open(os.path.join(fonts_dir, fn), "rb").read()
            blobs.append("    %r: %r,\n"
                         % (fn, base64.b64encode(data).decode("ascii")))
        elif fn == "LICENSES.md":
            lic = open(os.path.join(fonts_dir, fn), encoding="utf-8").read()
    fontdata = ("# generated by amalgamate_actaea.py: the bundled faces\n"
                "FONTS = {\n" + "".join(blobs) + "}\n"
                + "LICENSES = %r\n" % lic)
    modules.insert(modules.index("gui.app"), "gui.fontdata")
    module_srcs["gui.fontdata"] = fontdata
    # THE STAR RIDES INSIDE TOO (Actaea 2.0 dressing): the icons directory
    # becomes gui.icondata, and gui/dress.py unpacks it beside the fonts
    # when the loose files are not there (the standalone case).
    icons_dir = os.path.join(pkg_dir, "gui", "icons")
    icon_blobs = []
    for fn in sorted(os.listdir(icons_dir)):
        if fn.lower().endswith((".icns", ".ico", ".png")):
            data = open(os.path.join(icons_dir, fn), "rb").read()
            icon_blobs.append("    %r: %r,\n"
                              % (fn, base64.b64encode(data).decode("ascii")))
    icondata = ("# generated by amalgamate_actaea.py: the star, three ways\n"
                "ICONS = {\n" + "".join(icon_blobs) + "}\n")
    modules.insert(modules.index("gui.dress"), "gui.icondata")
    module_srcs["gui.icondata"] = icondata
    build_id = _fingerprint(init_src, module_srcs, modules)

    parts = [_HEADER]
    parts.append(f"\n_BUILD_ID = {build_id!r}\n")
    parts.append(f"\n_INIT = {init_src!r}\n")
    parts.append("\n_MODULES = {\n")
    for name in modules:
        parts.append(f"    {'actaea.' + name!r}: {module_srcs[name]!r},\n")
    parts.append("}\n")
    parts.append(_LOADER)
    script = "".join(parts)

    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as fh:
        fh.write(script)
    mode = os.stat(output_path).st_mode
    os.chmod(output_path, mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    print(f"wrote {output_path} ({len(script)} bytes, build {build_id})")


def main(argv: list[str]) -> int:
    output = argv[0] if argv else os.path.join("build", "actaea")
    build(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
