#!/usr/bin/env python3
# scalegen.py
# part of Arcturus, a programming language and compiler for the Infocom Z-machine.
# Copyright (c) 2026, Stefan Vogt.
# https://github.com/ByteProject/Arcturus

"""Generate a synthetic story at Hibernated 2 scale, for the B8 smoke test.

The real H2 compiles (under Inform 6) to 126 objects, 31 attributes, 175
globals, 102 verbs, 904 dictionary entries, and a 134.5K z5 story. This tool
writes a .storyarc that meets or exceeds those numbers, so the whole Arcturus
toolchain (compiler, Cosmos, DCE, abbreviations, the stats ledger, Frotz) is
exercised at real-game scale BEFORE the port starts, and any ceiling or
breakage surfaces in an afternoon rather than mid-port.

Deterministic (fixed seed), so two runs produce byte-identical source.

Usage:
    python3 tools/scalegen.py [output.storyarc]     # default: build/scale-smoke.storyarc

The generated game is playable: an 8x8 grid of connected rooms; the start room
holds a takeable token, a crate with a chip inside, a locked hatch east with
its key present, and scenery grains (some words deliberately shared across
rooms, exercising the grain chains). Characters with topics, daemons, custom
verbs, custom attributes, and a heavy load of prose round out the profile.
"""

from __future__ import annotations

import os
import random
import sys

R = random.Random(20260702)

GRID = 8  # 8x8 rooms = 64 rooms

# Vocabulary banks for deterministic pseudo-prose. Real-word distribution, so
# the abbreviation optimizer behaves as it would on genuine English text.
_ADJ = ["silent", "frozen", "pale", "ancient", "humming", "sealed", "dim",
        "vaulted", "narrow", "scarred", "gleaming", "hollow", "patient",
        "endless", "broken", "cold", "faint", "heavy", "distant", "slow"]
_NOUN = ["corridor", "bulkhead", "conduit", "terminal", "girder", "hatchway",
         "vent", "cable run", "deck plate", "stanchion", "coolant line",
         "service duct", "light strip", "column", "railing",
         "panel", "grate", "junction box", "walkway", "airlock ring"]
_VERBP = ["hums under the", "curves past the", "vanishes behind the",
          "leans against the", "drips onto the", "stretches toward the",
          "flickers above the", "rests beside the", "runs along the",
          "fades into the"]
_TAIL = ["and the air tastes of iron.", "and nothing moves.",
         "and the silence holds its breath.", "and dust hangs in the light.",
         "and the floor thrums softly.", "and the cold presses closer.",
         "and something ticks far away.", "and the shadows keep their place.",
         "and the station dreams on.", "and no one has passed for years."]

_VERBS = ["calibrate", "analyze", "activate", "deactivate", "override",
          "reroute", "scan", "probe", "vent", "purge", "prime", "engage",
          "disengage", "decode", "encode", "splice", "patch", "reboot",
          "align", "focus", "charge", "drain", "seal", "unseal", "deploy",
          "retract", "hail", "signal", "ping", "trace", "sample", "measure",
          "weld", "cut", "pry", "grease", "polish", "inspect", "log",
          "archive", "transmit", "receive", "amplify", "dampen", "shield",
          "expose", "rotate", "invert", "elevate", "lower", "anchor",
          "release", "spin", "brake", "dock"]

_ATTRS = ["charged", "sealed_tight", "dusty", "frosted", "humming_now",
          "corroded", "calibrated", "shielded", "magnetized", "leaking",
          "labeled", "sterile"]

_THING_NOUNS = ["wrench", "canister", "datapad", "coil", "fuse", "lens",
                "beacon", "cell", "valve", "gasket", "sensor", "module",
                "crystal", "rod", "clamp", "spool", "filter", "gauge",
                "relay", "capacitor", "manifold", "bracket", "socket",
                "adapter", "cartridge", "regulator", "injector", "actuator",
                "resonator", "emitter"]


# Compound-word bank for extra vocabulary: realistic station-speak, guaranteed
# distinct within the dictionary's nine-z-character truncation window.
_W1 = ["vent", "coil", "flux", "grid", "core", "beam", "node", "port", "duct",
       "cell", "rail", "seal", "clamp", "probe", "relay", "servo", "gyro",
       "pump", "sump", "lath"]
_W2 = ["cap", "pin", "rig", "kit", "tab", "pad", "jack", "lock", "ring",
       "bolt", "plug", "disc", "band", "stud", "gate"]
_COMPOUNDS = [a + b for a in _W1 for b in _W2]  # 300 distinct words


def _sentence() -> str:
    return (f"The {R.choice(_ADJ)} {R.choice(_NOUN)} {R.choice(_VERBP)} "
            f"{R.choice(_ADJ)} {R.choice(_NOUN)}, {R.choice(_TAIL)}")


def _prose(sentences: int) -> str:
    return " ".join(_sentence() for _ in range(sentences))


def _room_name(r, c) -> str:
    return f"sector{r}{c}"


def generate() -> str:
    out = []
    w = out.append

    w("// scale-smoke.storyarc, GENERATED by tools/scalegen.py: the B8 scale")
    w("// smoke test at Hibernated 2 scale. Do not edit; regenerate instead.")
    w("")
    w("summon.statusline")
    w("summon.conversations")
    w("")
    w("game")
    w('    title  "Scale Smoke"')
    w('    headline "The B8 scale smoke test"')
    w('    author "tools/scalegen.py"')
    w(f"    start  {_room_name(0, 0)}")
    w("")

    # Globals: with Cosmos's ~22 builtin slots this lands near H2's 175.
    w("// 155 game globals (H2 uses 175 of the Z-machine's 240).")
    for i in range(155):
        w(f"global counter{i:03d} = {R.randint(0, 500)}")
    w("")

    # Daemons.
    w("on start")
    w("    every 3 turns do pulse_one")
    w("    every 5 turns do pulse_two")
    w("    after 7 turns do pulse_once")
    w("")
    w("block pulse_one()")
    w("    if here is not sector00")
    w("        return 0")
    w(f'    say "{_sentence()}"')
    w("")
    w("block pulse_two()")
    w("    change counter001 to counter001 + 1")
    w("")
    w("block pulse_once()")
    w(f'    say "{_sentence()}"')
    w("")

    # The 8x8 room grid, heavy prose, grains everywhere; the word "dust" is
    # deliberately shared by MANY rooms (the grain-chain stress).
    for r in range(GRID):
        for c in range(GRID):
            name = _room_name(r, c)
            w(f"room {name}")
            w(f'    name "Sector {r}-{c}"')
            w(f'    desc "{_prose(8)}"')
            if c < GRID - 1:
                w(f"    east {_room_name(r, c + 1)}")
            if c > 0 and not (r == 0 and c == 1):
                w(f"    west {_room_name(r, c - 1)}")
            if r < GRID - 1:
                w(f"    south {_room_name(r + 1, c)}")
            if r > 0:
                w(f"    north {_room_name(r - 1, c)}")
            w("")
            w("    grains")
            w(f'        examine "dust" or "grime" say "{_sentence()}"')
            w(f'        examine "walls" or "wall" say "{_sentence()}"')
            w(f'        examine "{_COMPOUNDS[(r * GRID + c) % len(_COMPOUNDS)]}" say "{_sentence()}"')
            w("")

    # The start room's known props, for the scripted Frotz walk. The locked
    # hatch overrides the grid link east from sector00 to sector01.
    w("thing token in sector00")
    w('    name "brass token"')
    w("    words brass, token, coin")
    w(f'    desc "{_prose(1)}"')
    w("")
    w("thing crate of container in sector00")
    w('    name "steel crate"')
    w("    words steel, crate")
    w("    openable")
    w("    open false")
    w(f'    desc "{_prose(1)}"')
    w("")
    w("thing chip in crate")
    w('    name "data chip"')
    w("    words data, chip")
    w(f'    desc "{_prose(1)}"')
    w("")
    w("thing hatch of door in sector00, sector01")
    w('    name "sealed hatch"')
    w("    words sealed, hatch")
    w("    lockable")
    w("    locked")
    w("    unseal_with magkey")
    w("")
    w("thing magkey in sector00")
    w('    name "magnetic key"')
    w("    words magnetic, key, magkey")
    w(f'    desc "{_prose(1)}"')
    w("")
    # Route the grid's own east link through the hatch.
    w(f"// sector00's east goes through the hatch (declared above as a door).")
    w("")

    # ~60 scattered things: takeables, fixed scenery with intro, containers,
    # custom attributes sprinkled on.
    rooms = [_room_name(r, c) for r in range(GRID) for c in range(GRID)]
    thing_no = 0
    for i, noun in enumerate(_THING_NOUNS):
        for variant in ("a", "b"):
            thing_no += 1
            room = R.choice(rooms[1:])
            ident = f"item_{noun}_{variant}".replace(" ", "_")
            adj = R.choice(_ADJ)
            w(f"thing {ident} in {room}")
            w(f'    name "{adj} {noun}"')
            extra = [_COMPOUNDS[(thing_no * 3 + k) % len(_COMPOUNDS)] for k in range(3)]
            w(f"    words {adj}, {noun}, {', '.join(extra)}")
            w(f'    desc "{_prose(4)}"')
            if variant == "b":
                w("    fixed")
                w(f'    intro "{_sentence()}"')
            attr = R.choice(_ATTRS)
            if R.random() < 0.5:
                w(f"    {attr}")
            w("")

    # 8 characters with topics (the conversations menu at scale).
    for i in range(8):
        room = rooms[(i * 7 + 3) % len(rooms)]
        w(f"thing crew{i} of character in {room}")
        w(f'    name "crew member {i}"')
        w(f"    words crew, member, crew{i}")
        w("")
        for t in range(3):
            w(f'    topic t{i}_{t} "ask about matter {t}"')
            w(f'        you "Tell me about matter {t}."')
            w(f'        reply "{_prose(4)}"')
            w("")

    # 55 custom verbs, each with its own action and a free handler: with
    # Cosmos's ~47 standard verbs this lands at H2's 102.
    w("// 55 custom verbs (Cosmos's standard set brings the total past 100).")
    for i, v in enumerate(_VERBS):
        syn = _COMPOUNDS[-(i + 1)]
        w(f'verb "{v}", "{syn}"')
        w(f"    act_{v}")
        w("")
        w(f"on act_{v}")
        w(f'    say "{_prose(2)}"')
        w("")

    return "\n".join(out) + "\n"


def main() -> int:
    dest = sys.argv[1] if len(sys.argv) > 1 else os.path.join("build", "scale-smoke.storyarc")
    os.makedirs(os.path.dirname(dest) or ".", exist_ok=True)
    src = generate()
    with open(dest, "w", encoding="utf-8") as fh:
        fh.write(src)
    lines = src.count("\n")
    print(f"scalegen: wrote {dest} ({lines} lines, {len(src)} chars)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
